### ISSUE TITLE
Html buttons issuse

### ISSUE THREAD

**Issue by Irishtrekkie** [derme302/gmh#5]
in the example with a 2nd room added

Note how the buttons to go to another room do not work.
But they work properly as soon as the html object is removed from room1.

could be fixed by adding:
_Function to detect when HTML button is clicked.
_Function to return whether HTML checkbox is checked or not.

https://www.dropbox.com/s/kdzbk0cfbkwntbj/html%20multiple%20rooms.gmx.zip?dl=0

**Comment by derme302** [comment]
Adding gmh_canvas_html_active_element() should fix the issue with toggling browser_input_capture.

However I like the checkboxes idea, so in a coming version I'll extend gmh_canvas_html_get_value(id) to work with checkboxes.

Better support for buttons is on the list too.

**Comment by derme302** [comment]
Added in 289fd8a319a8431dc8ed22f7ee54bad227477b4e
